name: ci

on:
  push:

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
  B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - uses: actions/cache@v2.1.6
        with:
          path: |
            **/public
            **/resources
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/setup-node@v2.2.0
      - uses: peaceiris/actions-hugo@v2
      - name: Build
        run: yarn install && gulp ci

      ## TODO: Add some tests
      #- name: Test
      #  run: yarn install && gulp test

      - name: Deploy to Netlify (dev)
        uses: nwtgck/actions-netlify@v1.2
        id: netlify
        with:
          publish-dir: './public'
          production-deploy: false
          github-deployment-environment: 'dev'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        timeout-minutes: 1

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@7.0.0
        with:
          urls: |
            ${{ steps.netlify.outputs.deploy-url }}
            ${{ steps.netlify.outputs.deploy-url }}/blog/
            ${{ steps.netlify.outputs.deploy-url }}/gallery/
            ${{ steps.netlify.outputs.deploy-url }}/gallery/street-01-2020/
          budgetPath: ./.github/lighthouse/budget.json
          uploadArtifacts: true

      - name: Deploy to Netlify (prod)
        if: github.ref == 'refs/heads/master'
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './public'
          production-deploy: true
          github-deployment-environment: 'prod'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        timeout-minutes: 1
