---
name: ci

on:
  - push
  - pull_request_target

permissions: read-all
  # down scope as necessary via https://docs.github.com/en/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
  B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      # - uses: actions/cache@v3
      #   with:
      #     path: |
      #       **/public
      #       **/resources
      #       **/node_modules
      #     key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/setup-node@v3
      - uses: peaceiris/actions-hugo@v2
      - name: Build
        run: yarn install && gulp ci

      - name: Deploy to Netlify (dev)
        uses: nwtgck/actions-netlify@v2.0
        id: netlify
        with:
          publish-dir: './public'
          production-deploy: false
          github-deployment-environment: 'dev'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        timeout-minutes: 1

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@9.3.1
        with:
          urls: |
            ${{ steps.netlify.outputs.deploy-url }}
            ${{ steps.netlify.outputs.deploy-url }}/blog/
            ${{ steps.netlify.outputs.deploy-url }}/gallery/
            ${{ steps.netlify.outputs.deploy-url }}/gallery/street-01-2020/
          budgetPath: ./.github/lighthouse/budget.json
          uploadArtifacts: true

      - name: Deploy to Netlify (prod)
        if: github.ref == 'refs/heads/master'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './public'
          production-deploy: true
          github-deployment-environment: 'prod'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        timeout-minutes: 1
